export const RACE = {
  name: "152nd Kentucky Derby",
  track: "Churchill Downs",
  location: "Louisville, KY",
  date: "May 2, 2026",
  postTime: "7:02 PM ET",
  distance: "1.25 miles (10 furlongs)",
  surface: "Dirt",
  condition: "FAST",
  purse: "$5,000,000",
  winnerPurse: "$3,100,000",
  weather: "58°F, mostly cloudy, rain cleared",
  runners: 19,
  trifectaJackpot: "$16,420,488",
  superfectaPool: "$3,969,085",
  exactaPool: "$13,558,594",
  superHi5Pool: "$321,902",
  totalWinPool: "$35,838,975",
  paceScenario:
    "HOT. Six Speed (post 17) confirmed front-runner. Litmus Test (post 4) also speed. Hot early pace favors closers and stalkers positioned 4th-8th at Churchill Downs.",
  keySignal:
    "So Happy moved from 15/1 ML to 5/1 live — largest sharp move in the field. Renegade faded from 4/1 ML to 6/1 — market actively fading the morning line favorite.",
};

export const FIELD = [
  {
    post: 1, name: "Renegade", oddsDisplay: "6/1", dec: 7.0, mlDec: 5.0,
    beyer: 101, equibase: 107, style: "closer", starts: 5, foreign: false,
    lastYearCombo: false, eliteJ: true, jDerby: 0, jWinPct: 0.18,
    eliteT: true, tDerby: 2, tWinPct: 0.18,
    baffert: false, bounceRisk: false, formCollapse: false, maiden: false,
    postGroup: "p1", color: "#dc2626",
    jockeyName: "Irad Ortiz Jr.", trainerName: "Todd Pletcher",
    jockeyHot: false,
    mlMove: "FADING — drifted from 4/1 ML to 6/1. Market actively fading the morning line favorite.",
    notes: "Post 1 is 0-for-40 since Ferdinand 1986. Closer on rail in 19-horse field = structural nightmare. Irad chose him over Further Ado and Commandment. Talent is real. Post is fatal for his running style.",
  },
  {
    post: 2, name: "Albus", oddsDisplay: "44/1", dec: 45.0, mlDec: 31.0,
    beyer: 91, equibase: 91, style: "stalker", starts: 5, foreign: false,
    lastYearCombo: false, eliteJ: false, jDerby: 0, jWinPct: 0.23,
    eliteT: false, tDerby: 0, tWinPct: 0.17,
    baffert: false, bounceRisk: false, formCollapse: false, maiden: false,
    postGroup: "inner", color: "#6b7280",
    jockeyName: "Manuel Franco", trainerName: "Riley Mott",
    jockeyHot: false, mlMove: "Drifted from 30/1 ML",
    notes: "Won Wood Memorial but Beyer 91 fails the 100+ historical filter.",
  },
  {
    post: 3, name: "Intrepido", oddsDisplay: "47/1", dec: 48.0, mlDec: 51.0,
    beyer: 85, equibase: 85, style: "stalker", starts: 4, foreign: false,
    lastYearCombo: false, eliteJ: false, jDerby: 0, jWinPct: 0.18,
    eliteT: false, tDerby: 0, tWinPct: 0.22,
    baffert: false, bounceRisk: false, formCollapse: false, maiden: false,
    postGroup: "inner", color: "#6b7280",
    jockeyName: "Hector Berrios", trainerName: "Jeff Mullins",
    jockeyHot: false, mlMove: "Stable",
    notes: "Well below Beyer threshold. No realistic path.",
  },
  {
    post: 4, name: "Litmus Test", oddsDisplay: "25/1", dec: 26.0, mlDec: 51.0,
    beyer: 78, equibase: 78, style: "speed", starts: 5, foreign: false,
    lastYearCombo: false, eliteJ: false, jDerby: 0, jWinPct: 0.08,
    eliteT: true, tDerby: 6, tWinPct: 0.30,
    baffert: true, bounceRisk: false, formCollapse: true, maiden: false,
    postGroup: "inner", color: "#d97706",
    jockeyName: "Martin Garcia", trainerName: "Bob Baffert",
    jockeyHot: false,
    mlMove: "NOTABLE — shortened from 50/1 ML to 25/1. Form doesn't justify it.",
    notes: "7th by 12+ lengths in Arkansas Derby. Garcia gate-antics history. Baffert name only. Hard fade despite the tote move.",
  },
  {
    post: 6, name: "Commandment", oddsDisplay: "5/1", dec: 6.0, mlDec: 7.0,
    beyer: 101, equibase: 101, style: "closer", starts: 5, foreign: false,
    lastYearCombo: false, eliteJ: true, jDerby: 0, jWinPct: 0.16,
    eliteT: true, tDerby: 1, tWinPct: 0.26,
    baffert: false, bounceRisk: false, formCollapse: false, maiden: false,
    postGroup: "inner", color: "#1d4ed8",
    jockeyName: "Luis Saez", trainerName: "Brad H. Cox",
    jockeyHot: false, mlMove: "Shortened slightly from 6/1 ML",
    notes: "Multiple 100+ Beyers, Florida Derby winner. BUT both Irad AND Prat passed on him — loud jockey signal. Slow Florida Derby time vs recent winners.",
  },
  {
    post: 7, name: "Danon Bourbon", oddsDisplay: "14/1", dec: 15.0, mlDec: 21.0,
    beyer: null, equibase: null, style: "stalker", starts: 3, foreign: true,
    lastYearCombo: false, eliteJ: false, jDerby: 0, jWinPct: 0.33,
    eliteT: false, tDerby: 0, tWinPct: 0.0,
    baffert: false, bounceRisk: false, formCollapse: false, maiden: false,
    postGroup: "sweet", color: "#b45309",
    jockeyName: "Atsuya Nishimura", trainerName: "Manabu Ikezoe",
    jockeyHot: false, mlMove: "Shortened from 20/1 ML",
    notes: "Unbeaten. Best Fukuryu Stakes time in 20+ years. American-bred, sire record at Churchill. Post 7 is prime real estate. Japan form unverifiable. Exotic-only dart at 14/1.",
  },
  {
    post: 8, name: "So Happy", oddsDisplay: "5/1", dec: 6.0, mlDec: 16.0,
    beyer: 100, equibase: 100, style: "stalker", starts: 5, foreign: false,
    lastYearCombo: false, eliteJ: true, jDerby: 1, jWinPct: 0.12,
    eliteT: false, tDerby: 0, tWinPct: 0.18,
    baffert: false, bounceRisk: false, formCollapse: false, maiden: false,
    postGroup: "sweet", color: "#7c3aed",
    jockeyName: "Mike E. Smith", trainerName: "Mark Glatt",
    jockeyHot: false,
    mlMove: "🔥 MASSIVE STEAM — 15/1 ML to 5/1 live. Largest sharp move in the field.",
    notes: "ONLY horse to clear 100 across ALL FOUR major speed systems: Beyer 100, Brisnet 103, Equibase 100, TimeformUS 121. Post 8 historically excellent. Hall of Famer Mike Smith. The money move today is undeniable. Sire Runhappy stamina concern at 1.25mi is the only knock.",
  },
  {
    post: 10, name: "Wonder Dean", oddsDisplay: "25/1", dec: 26.0, mlDec: 31.0,
    beyer: null, equibase: null, style: "stalker", starts: 4, foreign: true,
    lastYearCombo: false, eliteJ: false, jDerby: 0, jWinPct: 0.33,
    eliteT: false, tDerby: 0, tWinPct: 0.0,
    baffert: false, bounceRisk: false, formCollapse: false, maiden: false,
    postGroup: "sweet", color: "#6b7280",
    jockeyName: "Ryusei Sakai", trainerName: "Daisuke Takayanagi",
    jockeyHot: false, mlMove: "Shortened from 30/1 ML",
    notes: "UAE Derby winner. UAE-based horses historically 0-for in the Kentucky Derby. No verifiable speed figures.",
  },
  {
    post: 11, name: "Incredibolt", oddsDisplay: "25/1", dec: 26.0, mlDec: 21.0,
    beyer: 88, equibase: 88, style: "closer", starts: 6, foreign: false,
    lastYearCombo: false, eliteJ: false, jDerby: 0, jWinPct: 0.11,
    eliteT: false, tDerby: 0, tWinPct: 0.15,
    baffert: false, bounceRisk: false, formCollapse: false, maiden: false,
    postGroup: "sweet", color: "#78716c",
    jockeyName: "Jaime Torres", trainerName: "Riley Mott",
    jockeyHot: false, mlMove: "Drifted from 20/1 ML",
    notes: "2-for-2 at Churchill Downs. Beyer 88 fails the 100+ filter. 7-week layoff exceeds recent winner threshold.",
  },
  {
    post: 12, name: "Chief Wallabee", oddsDisplay: "7/1", dec: 8.0, mlDec: 9.0,
    beyer: 100, equibase: 100, style: "stalker", starts: 3, foreign: false,
    lastYearCombo: true, eliteJ: true, jDerby: 1, jWinPct: 0.15,
    eliteT: true, tDerby: 1, tWinPct: 0.17,
    baffert: false, bounceRisk: false, formCollapse: false, maiden: false,
    postGroup: "sweet", color: "#16a34a",
    jockeyName: "Junior Alvarado", trainerName: "William I. Mott",
    jockeyHot: false, mlMove: "Stable at 7/1",
    notes: "EXACT same trainer+jockey (Mott+Alvarado) that won this race last year with Sovereignty. 100 Beyer. Post 12 ideal. First time blinkers. Only 3 career starts. Mott is deliberate — if he's running him, he's ready.",
  },
  {
    post: 14, name: "Potente", oddsDisplay: "18/1", dec: 19.0, mlDec: 21.0,
    beyer: 100, equibase: 100, style: "speed", starts: 3, foreign: false,
    lastYearCombo: false, eliteJ: false, jDerby: 0, jWinPct: 0.24,
    eliteT: true, tDerby: 6, tWinPct: 0.30,
    baffert: true, bounceRisk: false, formCollapse: false, maiden: false,
    postGroup: "sweet", color: "#b91c1c",
    jockeyName: "Juan Hernandez", trainerName: "Bob Baffert",
    jockeyHot: false, mlMove: "Shortened slightly from 20/1",
    notes: "Better Baffert horse. Beyer trending 83→94→100. Ran 2nd in Santa Anita Derby. Baffert has 6 Derby wins. Speed style hurts in hot pace scenario but 18/1 is solid price.",
  },
  {
    post: 15, name: "Emerging Market", oddsDisplay: "9/1", dec: 10.0, mlDec: 16.0,
    beyer: 90, equibase: 90, style: "closer", starts: 2, foreign: false,
    lastYearCombo: false, eliteJ: true, jDerby: 1, jWinPct: 0.25,
    eliteT: true, tDerby: 0, tWinPct: 0.24,
    baffert: false, bounceRisk: false, formCollapse: false, maiden: false,
    postGroup: "sweet", color: "#0891b2",
    jockeyName: "Flavien Prat", trainerName: "Chad C. Brown",
    jockeyHot: true,
    mlMove: "Shortened from 15/1 to 9/1. Prat money coming in.",
    notes: "Prat (25% win rate — highest jockey in field) chose this over Commandment. Brown (24% trainer rate) bringing him = endorsement. jockeyHot=true (Prat won 2 races on undercard today). FAILS: Beyer only 90 (below 100+ filter), only 2 career starts (fails since 1883), Brown 0-for-14 Derby career.",
  },
  {
    post: 16, name: "Pavlovian", oddsDisplay: "47/1", dec: 48.0, mlDec: 31.0,
    beyer: 85, equibase: 85, style: "speed", starts: 10, foreign: false,
    lastYearCombo: false, eliteJ: false, jDerby: 0, jWinPct: 0.14,
    eliteT: false, tDerby: 0, tWinPct: 0.10,
    baffert: false, bounceRisk: false, formCollapse: false, maiden: false,
    postGroup: "outer", color: "#6b7280",
    jockeyName: "Edwin Maldonado", trainerName: "Doug O'Neill",
    jockeyHot: false, mlMove: "Drifted from 30/1",
    notes: "Lost by a head to Emerging Market in Louisiana Derby. Below Beyer threshold.",
  },
  {
    post: 17, name: "Six Speed", oddsDisplay: "35/1", dec: 36.0, mlDec: 51.0,
    beyer: 84, equibase: 84, style: "speed", starts: 5, foreign: false,
    lastYearCombo: false, eliteJ: false, jDerby: 0, jWinPct: 0.15,
    eliteT: false, tDerby: 0, tWinPct: 0.0,
    baffert: false, bounceRisk: false, formCollapse: false, maiden: false,
    postGroup: "p17", color: "#6b7280",
    jockeyName: "Brian Hernandez Jr.", trainerName: "Bhupat Seemar",
    jockeyHot: false, mlMove: "Shortened from 50/1 ML",
    notes: "Post 17: 0-for-46 ALL TIME. Never produced a Derby winner. Primary pace-setter — will burn fractions early and set up the closers and stalkers in the stretch.",
  },
  {
    post: 18, name: "Further Ado", oddsDisplay: "6/1", dec: 7.0, mlDec: 7.0,
    beyer: 106, equibase: 107, style: "stalker", starts: 5, foreign: false,
    lastYearCombo: false, eliteJ: true, jDerby: 3, jWinPct: 0.18,
    eliteT: true, tDerby: 1, tWinPct: 0.26,
    baffert: false, bounceRisk: true, formCollapse: false, maiden: false,
    postGroup: "outer", color: "#15803d",
    jockeyName: "John R. Velazquez", trainerName: "Brad H. Cox",
    jockeyHot: true,
    mlMove: "Stable at 6/1. Projected actual favorite per double-pool math at ~4.8/1.",
    notes: "106 Beyer — field-best by 5 points. 11-length Blue Grass demolition. Cox specifically wanted outside post, got it. Velazquez won 2 races on today's undercard (jockeyHot). CONCERN: both big wins at Keeneland only, not Churchill. Figure jump 92→106 = bounce candidate.",
  },
  {
    post: 19, name: "Golden Tempo", oddsDisplay: "25/1", dec: 26.0, mlDec: 31.0,
    beyer: 88, equibase: 88, style: "closer", starts: 6, foreign: false,
    lastYearCombo: false, eliteJ: false, jDerby: 0, jWinPct: 0.22,
    eliteT: false, tDerby: 0, tWinPct: 0.22,
    baffert: false, bounceRisk: false, formCollapse: false, maiden: false,
    postGroup: "outer", color: "#6b7280",
    jockeyName: "Jose Ortiz", trainerName: "Cherie DeVaux",
    jockeyHot: false, mlMove: "Shortened from 30/1",
    notes: "Below Beyer threshold. Post 19 adds extra ground.",
  },
  {
    post: 21, name: "Great White", oddsDisplay: "23/1", dec: 24.0, mlDec: 51.0,
    beyer: 85, equibase: 85, style: "stalker", starts: 7, foreign: false,
    lastYearCombo: false, eliteJ: false, jDerby: 0, jWinPct: 0.14,
    eliteT: false, tDerby: 0, tWinPct: 0.09,
    baffert: false, bounceRisk: false, formCollapse: false, maiden: false,
    postGroup: "far", color: "#94a3b8",
    jockeyName: "Alex Achard", trainerName: "John Ennis",
    jockeyHot: false,
    mlMove: "NOTABLE — from 50/1 ML to 23/1. Likely public money not sharp.",
    notes: "Gray gelding. Historical bias against gray geldings in Derby. Below Beyer threshold.",
  },
  {
    post: 22, name: "Ocelli", oddsDisplay: "77/1", dec: 78.0, mlDec: 51.0,
    beyer: 82, equibase: 82, style: "closer", starts: 7, foreign: false,
    lastYearCombo: false, eliteJ: false, jDerby: 0, jWinPct: 0.13,
    eliteT: false, tDerby: 0, tWinPct: 0.13,
    baffert: false, bounceRisk: false, formCollapse: false, maiden: true,
    postGroup: "far", color: "#6b7280",
    jockeyName: "Tyler Gaffalione", trainerName: "D. Beckman",
    jockeyHot: false, mlMove: "Drifted",
    notes: "Maiden horse. No maiden has won the Kentucky Derby since 1882. Replacement draw.",
  },
  {
    post: 23, name: "Robusta", oddsDisplay: "76/1", dec: 77.0, mlDec: 51.0,
    beyer: 80, equibase: 80, style: "speed", starts: 5, foreign: false,
    lastYearCombo: false, eliteJ: false, jDerby: 0, jWinPct: 0.16,
    eliteT: false, tDerby: 0, tWinPct: 0.10,
    baffert: false, bounceRisk: false, formCollapse: false, maiden: false,
    postGroup: "far", color: "#6b7280",
    jockeyName: "Cristian Torres", trainerName: "Doug O'Neill",
    jockeyHot: false, mlMove: "Drifted",
    notes: "Replacement draw. Post 23. Well below Beyer threshold. No realistic path.",
  },
];
